# strings to remove when processing section titles
title_clean = {r'\n': ' ', r'\ufeff': '', r' *\d+\.* *': '', r'\xa0': ' ', r'&': 'and'}


# standardized section titles
"""edge cases (need further investigation)
- theoretical framework
- implementation
- 'model'
- "recommendations"
- "outcomes",
- 'description' -> a combination of introduction and results, all from journal microPublication Biology
- 'diagnosis' -> results?
- 'analysis' / 'data analysis' / "statistical analyses", -> sometimes methods, sometimes results
- 'summary' is sometimes in place of abstract, sometimes as part of conclusion
- 'highlights'
"""
title_versions = {
    "introduction": [
        "aim",
        "introduction",
        "introduction and background",
        "introduction and importance" "main",
        "objective",
        "objectives",
        "⧉ introduction",
    ],
    "background": [
        "background",
        "literature review",
        "preliminaries",
        "related literature",
        "related work",
        "related works",
        "review",
        "theoretical background",
        "theory",
    ],
    "methods": [
        "computational details",
        "data",
        "data and methodologies",
        "data and methods",
        "data collection",
        "data description",
        "data records",
        "experimental design, materials and methods",
        "experimental methods",
        "material and method",
        "material and methods",
        "materials",
        "materials and equipment",
        "materials and method",
        "materials and methods",
        "measures",
        "method",
        "method details",
        "methodology",
        "methods",
        "methods/design",
        "methods and design",
        "methods and materials",
        "participants and methods",
        "patients and methods",
        "procedure",
        "research design",
        "research design and methods" "research methodology",
        "research methods and design",
        "star★methods",
        "statistical analysis",
        "subjects and methods",
        "technical validation",
    ],
    "case report": [
        "case",
        "case history",
        "case description",
        "case discussion",
        "case presentation",
        "case presentations",
        "case report",
        "case report/case presentation",
        "case reports",
        "case series",
        "case study",
        "cases presentation",
        "clinical case",
        "clinical history",
        "illustrative case",
        "past medical history",
        "patient and observation",
        "presentation of case",
    ],
    "outcome": ["outcome", "outcomes", "outcome and follow-up"],
    "experiment": [
        "experiment",
        "experiment 1",
        "experiment 2",
        "experimental",
        "experimental details",
        "experimental procedure",
        "experimental procedures",
        "experimental section",
        "experimental setup",
        "experiments",
    ],
    "treatment": ["treatment", "treatment plan", "treatment progress"],
    "diagnosis": [
        "diagnoses",
        "diagnosis",
        "final diagnosis",
        "differential diagnosis",
    ],
    "results": [
        "experimental results",
        "experimental results and analysis",
        "findings",
        "main results",
        "result",
        "results",
        "results and analysis",
        "⧉ results",
    ],
    "discussion": [
        "discussion",
        "discussions",
        "general discussion",
        "utility and discussion",
        "⧉ discussions",
    ],
    "conclusion": [
        "challenges and future directions",
        "clinical implications",
        "concluding remarks",
        "concluding remarks and future directions",
        "concluding remarks and future perspectives",
        "conclusion",
        "conclusion and future directions",
        "conclusion and future perspective",
        "conclusion and future perspectives",
        "conclusion and future work",
        "conclusion and outlook",
        "conclusion and perspective" "conclusion and perspectives",
        "conclusion and recommendations",
        "conclusions",
        "conclusions/outlook",
        "conclusions and future directions",
        "conclusions and future perspectives",
        "conclusions and future work",
        "conclusions and perspective",
        "conclusions and perspectives",
        "conclusions and prospects",
        "conclusions and outlook",
        "conclusions and recommendations",
        "final considerations",
        "future direction",
        "future directions",
        "future perspective",
        "future perspectives",
        "future research directions",
        "implications",
        "outlook",
        "perspectives",
        "summary and conclusion",
        "summary and conclusions",
        "summary and future perspectives" "summary and outlook",
        "summary and perspectives",
        "⧉ conclusions",
    ],
    "limitations": [
        "limitation",
        "limitation of the study",
        "limitations",
        "limitations of the study",
        "strengths and limitations",
        "study limitations",
    ],
    "summary": ["summary", "key messages", "key summary points", "key points"],
    "supplementary": [
        "supporting information",
        "supplementary information",
        "supplementary material",
        "electronic supplementary material",
        "supplemental material",
        "supplemental information",
        "online content",
        "abbreviations",
        "source data",
        "supplementary materials",
        "patents",
        "value of the data",
        "additional information",
        "supplementary data",
        "supplementary figures and tables",
        "trial status",
        "additional file",
        "taxonomy",
        "appendix",
        "supplementary material figures",
    ],
    "admin": [
        "author contributions",
        "conflicts of interest",
        "ethics statement",
        "conflict of interest",
        "conflict of interest statement",
        "declaration of competing interest",
        "credit authorship contribution statement",
        "funding",
        "consent",
        "data availability",
        "acknowledgments",
        "funding information",
        "declaration of interests",
        "conflict of interests",
        "disclosure",
        "ethical approval",
        "resource availability",
        "disclosures",
        "availability of data and materials",
        "competing interests",
        "declaration of generative ai and ai-assisted technologies in the writing process",
        "authors’ contributions",
        "consent for publication",
        "ethics approval and consent to participate",
        "contributors",
        "data availability statement",
        "peer review",
        "transparency statement",
        "data sharing statement",
        "ethics approval",
        "author contribution",
        "announcement",
        "declarations",
        "credit author statement",
        "disclaimer",
        "patient consent",
        "consent statement",
        "authors' contributions",
        "authors’ information",
        "availability of supporting data",
        "pre-publication history",
        "competing interest",
        "authors’ contribution",
        "additional files",
        "supplementary figures",
        "availability and requirements",
        "sources of funding",
        "acknowledgements",
    ],
    "combined": [
        "results and discussion",
        "discussion and conclusion",
        "result and discussion",
        "limitations and future directions",
        "background and summary",
        "methods and analysis",
        "experiments and results",
        "conclusion and discussion",
        "experimental results and discussion",
        "limitations and future research",
        "results and discussions",
        "discussion and conclusions",
    ],
    "misc": [
        "",
        "introdução",
        "resultados",
        "discussão",
        "chemical context",
        "synthesis and crystallization",
        "structural commentary",
        "supra\xadmolecular features",
        "refinement",
        "implementation",
    ],
}
